### ISSUE TITLE
Automatically publish package for each release

### ISSUE THREAD

**Issue by 11michalis11** [11michalis11/pykemon_battle#13]
PYPI_USERNAME and PYPI_PASSWORD are set in repository settings  **(Settings > Secrets > New repository secret)** or maybe use a [token](https://pypi.org/manage/account/token/)

## publish.yml: 
```
name: publish

on:
    release:
        types: [created]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.9"

            - name: Install dependencies
              run: |
                  make deps

            - name: Publish to PyPi
              env:
                  FLIT_USERNAME: ${{ secrets.PYPI_USERNAME }}
                  FLIT_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
              run: |
                  make publish
```
